# Generated by Django 2.1.7 on 2019-03-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='get_profiles', to='core.Skill', verbose_name='Habilidades'),
        ),
    ]
