# Generated by Django 2.1.7 on 2019-03-19 01:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190317_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=blog.models.custom_post_upload_to, verbose_name='Imagen (800x600)'),
        ),
    ]
