# Generated by Django 2.1.7 on 2019-03-07 04:47

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to=home.models.custom_slide_upload_to, verbose_name='Imagen'),
        ),
    ]
