# Generated by Django 2.1.7 on 2019-03-15 22:48

import ckeditor.fields
from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('image', models.ImageField(upload_to=portfolio.models.custom_photography_upload_to, verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('published', models.BooleanField(default=True, verbose_name='Publicar')),
                ('categories', models.ManyToManyField(related_name='get_drawings', to='portfolio.Category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Dibujo',
                'verbose_name_plural': 'Dibujos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('published', models.BooleanField(default=True, verbose_name='Publicar')),
                ('categories', models.ManyToManyField(related_name='get_poems', to='portfolio.Category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Poema',
                'verbose_name_plural': 'Poemas',
                'ordering': ['created'],
            },
        ),
    ]
