# Generated by Django 2.1.7 on 2019-03-17 20:29

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_drawing_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.custom_drawing_upload_to, verbose_name='Imagen'),
        ),
    ]
